name = "Promised World Client"
author = "ManyStars"
version = "1.0.0+pw.20251108"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce67338dd67af14210e6f22eb133d657b7fd98f5515c8819dfc903be5feb30d8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
