name = "Promised World Client"
author = "ManyStars"
version = "2.0.0+pw.20251119"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23bcac5c2ad414c8f93137758cf93f680713dee137d8af12f284cb18dad69a33"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
