name = "Promised World Client"
author = "ManyStars"
version = "2.1.0+pw.20251122"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "582d85d67074ea35f04004bf506188f9267a8254e2575f8bd55b12c2e3d9ff86"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
