name = "Promised World Client"
author = "ManyStars"
version = "3.0.0-beta.1+pw.20251208"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15a9446a322e1601632a4e05acc384ea2be3106cfd84f7967efc943a329c740c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
