name = "Promised World Client"
author = "ManyStars"
version = "1.0.0-beta.3+pw.20251105"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dce11a304815b1895927f2761966462ebd00bc72c2c6bf7a40a9327f8c3932b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
