name = "Promised World Client"
author = "ManyStars"
version = "2.0.0+pw.20251119"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b40a3b16550450f1c02ee0567c0122fa2e51fb2d2dc12d18a42ba8f49f0fe3ef"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
