
# #----------------------------------------------------------------------
#     欢迎您使用CSC，CSC（原名 Create:SchematicChecker | 机械动力：蓝图校验 ）
# 是专为机械动力与全部机械动力附属而定制的蓝图扫描模组,它可以阻止任何已经记录在案的潜在/恶性漏洞。
# 这些恶性漏洞包括但不限于：复制物品、卡顿服务器甚至崩溃服务器、获取创造物品、获取服务器控制权等。。
# 而触发它们仅需上传固定修改参数的蓝图，这使得破坏服务器变得轻而易举，只要服务器不禁用蓝图炮，那么任何人都可以随意的
# 以极低的成本和极少的时间破坏服务器、崩溃服务器、获取任意物品。
#   此模组转为此问题而设计，永久解决机械动力蓝图的弊病！
# CSC 允许用户自定义黑名单标签、方块，允许自定义剔除规则，允许对蓝图的校验结果进行详细的配置和自定义
# 由于蓝图的通用性，这使得CSC可以检测包括机械动力和机械动力的所有附属mod！
# 如果用户同意，CSC甚至可以选择联网更新自动同步规则到本地服务器，只要CSC团队发现了新的漏洞，
# 那么就会自动更新配置文件，来实现不需要重启服务器即可自动剔除潜在的漏洞。
# 选择默认的文件语言 zh_cn / en_us 
Language = "zh_cn"

UUID = "6e635c20-cd64-45e2-91b5-cca6b4a6723d"

[core]
    # #----------------------------------------------------------------------
    # 是否启用 CSC （机械动力：蓝图检查）
    Enable = true
    # #----------------------------------------------------------------------
    # 蓝图检查的超时时间
    DelayTime = 10
    # #----------------------------------------------------------------------
    # 是否启动白名单模式，推荐开启，可以直接根除不熟悉的mod导致的蓝图漏洞
    WhiteListModEnable = true
    # #----------------------------------------------------------------------
    # 只有填入此列表的mod才会允许保留nbt，填入modid 比如minecraft:dirt 那就填入minecraft
    WhiteListModList = [
        "create",
        "minecraft",
        "createdieselgenerators",
        "createrailwaysnavigator",
        "createaddition",
        "railways",
        "copycats",
        "createsifter",
        "computercraft",
        "yuushya" ]
    # #----------------------------------------------------------------------
    # 被禁止的方块或物品，如果被填入，CSC将尝试剔除方块实体内的对应物品。
    # 如果剔除失败，CSC会将该物品清除实体数据，方块仍然可以打印，但会失去nbt数据。
    BanBlock = [
        "create:creative_crate",
        "create:creative_fluid_tank",
        "create_integrated_farming:chicken_roost",
        "create:creative_motor",
        "create:creative_blaze_cake",
        "create:handheld_worldshaper",
        "minecraft:spawner",
        "twilightforest:giant_obsidian",
        "twilightforest:giant_leaves",
        "twilightforest:giant_log",
        "twilightforest:giant_cobblestone",
        "twilightforest:huge_lily_pad",
        "ae2:creative_item_cell",
        "ae2:creative_fluid_cell",
        "ae2:creative_energy_cell",
        "appmek:creative_chemical_cell",
        "vs_clockwork:creative_gravitron",
        "createbigcannons:creative_autocannon_ammo_container",
        "createaddition:creative_energy",
        "create_connected:creative_fluid_vessel",
        "destroy:creative_pump",
        "immersiveengineering:capacitor_creative",
        "mekanism:creative_bin",
        "mekanism:creative_fluid_tank",
        "mekanism:creative_energy_cube",
        "mekanism:creative_chemical_tank",
        "numismatics:creative_vendor",
        "mekanism_extras:upgrade_creative",
        "the_vmod:physgun",
        "the_vmod:toolgun",
        "Item.of('tacz:ammo_box', '{Creative:1b}')",
        "Item.of('tacz:ammo_box', '{AllTypeCreative:1b}')",
        "minecraft:command_block",
        "quark:grate",
        "minecraft:kelp" ]
    # #----------------------------------------------------------------------
    # 禁止标签，任何方块如果内部包含此列表的标签，都会被清除！
    BanTag = [
        "AttributeModifiers",
        "run_command",
        "using_converts_to",
        "bundle_contents",
        "minecraft:container",
        "minecraft:attribute_modifiers" ]
    # #----------------------------------------------------------------------
    # 是否清理实体，当设置为true后，蓝图内的实体会被清除，但不会清除填入白名单的实体。
    # 此功能启用可以阻止所有潜在的实体nbt复制漏洞，也可以阻止盔甲架获取创造物品
    # 此功能建议启用！
    KillEntity = true
    # #----------------------------------------------------------------------
    # 当KillEntity功能为false时，此功能将会启用，任何填入此列表的实体都会在蓝图中被删除。
    # 但不能删除白名单内的实体，因此不能同时与白名单填入相同的id
    BanEntity = [
        "minecraft:armor_stand",
        "create:crafting_blueprint" ]
    # #----------------------------------------------------------------------
    # 白名单的实体，不能与黑名单冲突，填入后的实体会被保留，在killEntity功能为true时启动
    # 注意，此功能只有下面的实体会被算法校验，其他实体都会保留nbt，使用默认匹配
    # 可匹配的物品：强力胶。
    whitelistEntity = [
        "create:super_glue" ]

[debug]
    # #----------------------------------------------------------------------
    # 是否在聊天界面输出检测蓝图的物品列表，这可能会刷屏，但是可以显示蓝图内的方块统计
    DebugTotalBlock = true
    # #----------------------------------------------------------------------
    # 当CSC发现作弊蓝图时，是否广播作弊者和作弊蓝图
    DebugCheatFind = true
    # #----------------------------------------------------------------------
    # 是否允许CSC对蓝图进行备份，此功能会在玩家每次上传后备份蓝图文件，以时间/玩家命名
    # 此功能强烈推荐开启，这可以在新的漏洞被发现时，通过扫描历史的上传备份来回溯上传历史！
    # 此功能会占用一些存储空间，因为会对每个上传蓝图进行储存。
    EnableBackup = true

[function]
    # #----------------------------------------------------------------------
    # 是否检测蓝图内传送带的完整性，如果不完整则会被视为漏洞蓝图，因为上千格的传送带可以卡服
    # 同时还会导致区块数据包含传送带实体，增加带宽，同时，不完整的传送带可以复制传动杆和传送带
    checkBelt = true
    # #----------------------------------------------------------------------
    # 当传送带被检测出不完整时，是否清除不完整的传送带而不是直接阻止蓝图
    # 此功能还在Beta版本，这可以在传送带不完整时，正常打印蓝图，只是不完整的传送带不会打印
    TryRemoveBeltNotKill = true
    # #----------------------------------------------------------------------
    # 传送带的最大允许不匹配数量，当蓝图内校验和不匹配的传送带数量超过这个阈值后，蓝图会被视为作弊蓝图
    # 当蓝图内的不匹配数量少于这个值时，将会剔除有问题的传送带
    maxBeltCheatLimit = 10
    # #----------------------------------------------------------------------
    # 链式传动轮的最大允许长度，机械动力默认为32 当蓝图内有超过这个距离的链式传动轮时，蓝图会被视为作弊蓝图
    # 当链式传动轮的长度低于这个阈值时，仅会剔除有问题的传动轮
    maxConveyorCheatDistanceLimit = 50
    # #----------------------------------------------------------------------
    # 传动轮的最大允许不匹配数量，当蓝图校验和不匹配的传动轮数量超过这个阈值后，蓝图会被视为作弊蓝图
    # 如果校验和不匹配数量少于这个值，蓝图仅会剔除有问题的传动轮
    maxConveyorCheatLimit = 10

[online]
    # #----------------------------------------------------------------------
    # 是否启用云端自动更新同步功能，转为服务器定制，注意，此功能需要联网！
    # 启用此功能后，CSC将会自动从云端同步最新的漏洞剔除规则
    # 但如果出现了异常蓝图或无法读取的蓝图，CSC会将这些蓝图上传至云端来加强云端规则
    # 因为云端检查需要蓝图样本才能不断更新，上传的蓝图仅会用于漏洞检测，不会用于任何其他用途
    # 启用此功能会收集部分蓝图数据，因此如果您使用此功能就代表允许CSC利用您的蓝图进行规则强化！
    enableAutoUpdate = false
    # #----------------------------------------------------------------------
    # 是否启用用户配置规则，当启用后，用户的额外配置文件会作为规则处理蓝图
    # id 是针对实体方块的剔除，用于banblock功能剔除不完全时的附加
    # 每个对象需要两个元素，物品的ID 和位置，可以通过NBTExplorer 软件来查询 
    # 默认情况下的路径使用.来分割，如果遇到列表，需要在列表标签前加入$ 来辅助识别
    # operate 是针对nbt的剔除功能，用于操作任意方块的nbt结构，具有极高的自由度
    # limit 当设置limit时，可以指定变量的上下限，需要使用 operate.limit$变量名$下限$上限  的格式
    # clear 当设置为清除时，对应的nbt会被剔除，需要使用 operate.clear$变量名  的格式
    # replace 当设置为替换时，对应的nbt标签会被替换 只能替换字符串，需要使用 operate.replace$变量名$结果 的格式
    enableManualConfig = false
    # #----------------------------------------------------------------------
    # 启动自动更新提醒，当设置为true，如果CSC有需要更新版本才能修复的漏洞，将会发出提醒
    UpdateInfo = true
    # #----------------------------------------------------------------------
    # 如果出现了CSC检测不了的蓝图是否自动上传，默认开启，这可以帮助更多的人，也可以让CSC变得更好！
    report = true
    [debug.debug]
        # #----------------------------------------------------------------------
        # 启动调试模式，这会打印更多的报错输出，但会导致控制台变得混乱，绝大多数情况下不需要开启
        problem = false
    # #----------------------------------------------------------------------
    # 链式传动轮的最大允许角度 原版默认为45° 任何大于此值都篡改了蓝图nbt，但此设置允许自定义
    maxConveyorAllowDegree = 45


