[general]
	#If this is set to false, the mod will not try to fetch the version data at all.
	enableVersionChecking = true
	#Extra text added before each line of changelog
	changelogPrefix = " - "
	#How much time to read before the connection closes with a timeout error.
	# Default: 5000
	# Range: 1000 ~ 30000
	versionCheckerReadTimeout = 5000
	#How much time to connect to the URL before the connection closes with a timeout error.
	# Default: 5000
	# Range: 1000 ~ 30000
	versionCheckerConnectTimeout = 5000
	#The name of your modpack
	modpackName = "Promised World Client"
	#Where the version data JSON will be fetched from, KEEP http:// or https://
	versionDataURL = "https://gitee.com/Star-River-Studios/Promised-World-Client/raw/main/update_data.json"
	#The url that is opened when the user clicks on update button, KEEP http:// or https://
	updateURL = "https://github.com/Star-River-Studios/Promised-World-Client/releases/latest"
	#The border of large messages, makes them look pretty
	delimiter = "========================================"

[notifications]
	#Display a chat message when logging into a world for the first time if an update is available?
	showLoginChatUpdateNotification = false
	#If 'welcomeMessage' key is defined in the JSON, display the message in chat when logging into a world
	showWelcomeMessage = false
	#If true, displays an error message in chat if this mod is unable to fetch all update data.
	showUpdateCheckFailedMessage = false

[currentVersion]
	#Version name of the current version
	versionName = "3.0.0-beta.1+pw.20251208"
	#Version code of the current version, must not be negative.
	# Default: 0
	# Range: > 0
	versionCode = 20251208
	#How to output formatted version name. Only used for displaying current version.
	versionFormat = "%currentVersionName%"
	#Variables to use when formatting current version. One entry per line, the format is key=value
	#Values must follow JSON element format, for example strings must be double quoted
	variables = []

[mainMenu]
	#Whether to enable main menu rendering added by this mod at all or not.
	enableMainMenu = true
	#Where to place the main menu text. Must be one of: TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT, TOP_CENTER, BOTTOM_CENTER, CENTER_LEFT, CENTER_RIGHT, CENTER
	menuTextPosition = "BOTTOM_LEFT"
	#How much space between main menu text and the border of the screen. (Horizontal)
	# Default: 2
	# Range: 0 ~ 100
	marginHorizontal = 2
	#How much space between main menu text and the border of the screen. (Vertical)
	# Default: 2
	# Range: 0 ~ 100
	marginVertical = 23
	#Default color of the main menu text. Must be converted into a decimal integer. (0xffffff -> 16777215)
	# Default: 16777215
	# Range: 0 ~ 16777215
	textColor = 16777215
	#Text to display on the main menu. You can use variables like %versionName% in the string.
	textLines = ["§eVersion§f: §9%currentVersionName%", "%isUpdateAvailable%"]
	#Text to display when hovering mouse over the text, as tooltips.
	tooltipText = ["§eCurrent Version§f: §6%currentVersionName% (%currentVersionCode%)", "§2Latest Version§f: §2%versionName% (%versionCode%)", "§9§nClick for update link!"]
	#When the user click on the text, they will be sent to this link.
	clickLink = "https://github.com/Star-River-Studios/Promised-World-Client/releases/latest"
