hash-format = "sha256"

[[files]]
file = "cache/chunksfadein/translations/af"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/ar"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/ca"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/cs"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/da"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/de"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/el"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/en"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/es-ES"
hash = "0a63633412ec308593a6597731c2ffd21f9638573455d1a3c08f1611fc13b679"

[[files]]
file = "cache/chunksfadein/translations/fi"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/fr"
hash = "43b50a40e716fbc891b303621417650766673417dcf31a03fde591ec529692b6"

[[files]]
file = "cache/chunksfadein/translations/he"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/hu"
hash = "abb80e9415f823aa8d3132d220f6c46743db91592615427eeb6a3cdb18e00ef5"

[[files]]
file = "cache/chunksfadein/translations/it"
hash = "cfe36895f18177e352742743dcd3b35efbb035917e92deb8aee779085e78ca9c"

[[files]]
file = "cache/chunksfadein/translations/ja"
hash = "90655ce6165fa53acab36e8679f0fdd1e5783909833075db9e7f52557a190cad"

[[files]]
file = "cache/chunksfadein/translations/ko"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/nl"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/no"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/pl"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/pt-BR"
hash = "76b7b2b1160279cea4c23bcf7024b7b11b692a23451904534f05c4adafe95af7"

[[files]]
file = "cache/chunksfadein/translations/pt-PT"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/ro"
hash = "c88362ad9f8fe2e7fffee97b85f6279d7cec8663e8357083841c10fdd062ae06"

[[files]]
file = "cache/chunksfadein/translations/ru"
hash = "4dfb9c07f85c98961fb927d7bbf19bfe2786c95d4e59e5f3b211b931fdf334b2"

[[files]]
file = "cache/chunksfadein/translations/sr"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/sv-SE"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/tr"
hash = "ad5c36801702a5832c4b699c6926139a37ca264170be134095b6187f24fe70df"

[[files]]
file = "cache/chunksfadein/translations/uk"
hash = "d1fe87fa1a747dea0b5328a2a20c7f927e9a65c58a58741f2d22cd82dc25153d"

[[files]]
file = "cache/chunksfadein/translations/vi"
hash = "8010ab040605c8249cf210c7fcf7b883f323e2b740f8fc52f43106ab83fb432a"

[[files]]
file = "cache/chunksfadein/translations/zh-CN"
hash = "4b29770840927bebaa560ff2dc86a02e4b700f0e80719e6718fa2910a53aec33"

[[files]]
file = "cache/chunksfadein/translations/zh-TW"
hash = "bc16c459ae645fbf5eac389cba7b24ca8c486f572ec47319c5ef96e1afb98efa"

[[files]]
file = "config/MouseTweaks.cfg"
hash = "4069ce1a439d8c37453c1b1e9f2037e0942674c7e48723a39b37eab245792ad4"

[[files]]
file = "config/appleskin.json5"
hash = "65edc28ca2bf6bd3e3684ae545fb74bcc0ec935a40d6ac60cb68c00c152e34fb"

[[files]]
file = "config/betteradvancements.json"
hash = "86b92c4716a03d328a6f98b66a894c5fa1568c5b3b83074c4d9ddcf518cc849c"

[[files]]
file = "config/chunksfadein.properties"
hash = "50de0c770717008172529787a6a4d785bf42224a25f164d02a0e194c80964eea"

[[files]]
file = "config/cursors_extended.json"
hash = "1645fbfc63964ead5bada17083323fc9e718a212a754f7c05ded78977696e12f"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "94624d39c8fc6972268172c414dbf0363e871eba5bd4bc113e106b4d2c222e27"

[[files]]
file = "config/fancytoasts/general.json"
hash = "bf600a5c47322201af6c8738c437ce2781f9241c6019c2168e7e2eb8062dff29"

[[files]]
file = "config/fancytoasts/toast.json"
hash = "1bd81d301399012ee5e699cccbe934ae1f53a26d6bc4873ce2a3df3639ec034d"

[[files]]
file = "config/fancytoasts/toast_filtering.json"
hash = "1a88586b9259f0aa429848c03b10ebabdd9b6261ca5ff322cb7bb68b9d442116"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "a2091a291309db8920c8a80e913ed31c24c29687d8cd25ac18076ad85a90ddb8"

[[files]]
file = "config/iris-excluded.json"
hash = "4d3264b58c502afaeca3f44e8d2db0843c54b8ba957afd21a2d450fe10dafefb"

[[files]]
file = "config/iris.properties"
hash = "d4a14a03f59b7532ff414d4382d3cff62b99cb10003f852fc2ebdcd38bb3fb67"

[[files]]
file = "config/jade/jade.json"
hash = "296c70fd6a4bffd150c5dc02c016dd4927e209e4f6c54ba0221ee2c623f0f2c5"

[[files]]
file = "config/jade/profiles/1/jade.json"
hash = "b78a0c24dc78612805066acb31be76e23423ae4a8392820aae1163fe90a47760"

[[files]]
file = "config/jade/profiles/2/jade.json"
hash = "470c98e9a24947a2eac8d5f6c1cf619840d2d93e6625b0557e80cfc7f3ad7fe6"

[[files]]
file = "config/jade/profiles/3/jade.json"
hash = "65ef88917bf7478cd42766b0394adda2b6837a130cdac74a948ee447c2309e0a"

[[files]]
file = "config/jade/sort-order.json"
hash = "c0235d429020dce0cd44eb11e34a728f83e8416ef5b61bd9607af370e963ad6c"

[[files]]
file = "config/modmenu.json"
hash = "3613be8de2a7479e52a5a26686a495d7ca6e702985d4d6acfb1273e58a35e161"

[[files]]
file = "config/nemos-inventory-sorting/config.json"
hash = "7b976efcdf2ecd96594419a6f9b7eadb6cc8b860b33df7130c65bc9f0a9b05f5"

[[files]]
file = "config/nemos-inventory-sorting/filter-config.json"
hash = "f5c5c6ef9722009416a429d0c263ab2bd34678351d0998b6ef43825013c83bdd"

[[files]]
file = "config/plasmovoice/.crowdin/de_de.json"
hash = "1fe30625fb96f11e1513d848a04bc4fbad707f4ad0ba61849a388a9e7a33ca9d"

[[files]]
file = "config/plasmovoice/.crowdin/es_es.json"
hash = "bcd62f8b59b77ed388231cbd6cd479f58aa82309788ba2a26410cb21e514adfa"

[[files]]
file = "config/plasmovoice/.crowdin/fr_fr.json"
hash = "6c2e91b1a964e5dd4511702fd554ac8094c4f862ab4679b7dbd54af18c128db0"

[[files]]
file = "config/plasmovoice/.crowdin/he_il.json"
hash = "81af917b226159198f9a76cb9caa4ffa5ba108684106d0a7d7a46a0e756f4a29"

[[files]]
file = "config/plasmovoice/.crowdin/ja_jp.json"
hash = "0db355eb21a7795e9e57bb94ae925a28efdbdec49b0704476dcf9c9dc2ed5566"

[[files]]
file = "config/plasmovoice/.crowdin/ko_kr.json"
hash = "8e0d47316caee0b490f6bedabb5532da30567094b6438deead1f3f0f85e66346"

[[files]]
file = "config/plasmovoice/.crowdin/pl_pl.json"
hash = "62a43c9f3d46b1e1630b1988ee07413139da25a57dc49265b8cc9450cbae0cfb"

[[files]]
file = "config/plasmovoice/.crowdin/pt_br.json"
hash = "b0e75ebd3798bdbe416ffb3ea3ac0bda766e3bcf92864821bab5a1f34e434a18"

[[files]]
file = "config/plasmovoice/.crowdin/ru_ru.json"
hash = "d968868df22341f8b07a1b35c2dbbeaee2c14a866037a00fdd6a0521b9d0e01b"

[[files]]
file = "config/plasmovoice/.crowdin/timestamp"
hash = "5f71b04b6849e36f6108f07f3f95f60c782f983ca1713073be011654d109787c"

[[files]]
file = "config/plasmovoice/.crowdin/tt_ru.json"
hash = "4437e99ad9a5a3c95a7522a149c97d83ed5755228e1a2ce6478cc6c447351157"

[[files]]
file = "config/plasmovoice/.crowdin/uk_ua.json"
hash = "3348f1728d61f8a274f99a73d03a6dbd3b43fa47662cce41035a8cad6cb36b60"

[[files]]
file = "config/plasmovoice/.crowdin/vi_vn.json"
hash = "9fc7b9669868da19f237629ff536155135e17e6c3a42f978bec98fb514aa0c25"

[[files]]
file = "config/plasmovoice/.crowdin/zh_cn.json"
hash = "b92d52b8ffbc46de6da360f5a785bc920cfc3c3885de6f373257110fc3ebc94c"

[[files]]
file = "config/plasmovoice/.crowdin/zh_tw.json"
hash = "14870f7731fe7381871e17a10d3cb962a041f31ae613cf6872e9debd20775a8c"

[[files]]
file = "config/plasmovoice/client.toml"
hash = "6bc27c0abf808d1ce9a6c3139100ef9c3f12199d060f57075793e3461292063a"

[[files]]
file = "config/plasmovoice/meta_cache.json"
hash = "5db3d17465b89c55dc44718498b52754634e689508c66e3088bf0bc52b5d929f"

[[files]]
file = "config/resourcify.json"
hash = "e58371e7d636e557efde9fecf278417fd1b5290f025fe79564bc57030eca1566"

[[files]]
file = "config/sodium-extra-options.json"
hash = "d44456ff4759b5920f8f4376241caa5e411291701649b07c747dc4dacd9a05e2"

[[files]]
file = "config/sodium-extra.properties"
hash = "a2f1b47c1eaa119ab34727f1d43c2506cb3d7f17ba8fb4efb49e20c8e0b58e70"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "e4013321f8860407d2c641253b954a4b0b52a3b0dc461f41aa98f26b4dec0be6"

[[files]]
file = "config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/sodium-options.json"
hash = "2b0725daa4052885bde7f195eb60501a5f6f9baadcb6e384c844660458b9fbaf"

[[files]]
file = "config/spark/tmp-client/about.txt"
hash = "d7514c0ddb6ae8611a281527bf04ca6cbcea1fa21758534fdcd08ed0f51c19c0"

[[files]]
file = "data/fabric_default_resource_packs.json"
hash = "72d4ef909f10e370d85f3d9315e3ac5292b648dd8c1e078b80cc86befd4a4be8"

[[files]]
file = "downloads/log.json"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "journeymap/config/6.0/journeymap.core.config"
hash = "215c984dba19d899e9af3c803066228b6d30e1950deda0d5418c2974768bae5a"

[[files]]
file = "journeymap/config/6.0/journeymap.fullmap.config"
hash = "f83fb010fd04ee0d3384071f59e6dc82645d171cda4f150a52a461f73731ffc3"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "24b2ed037121203bcdcebda627e1e7ca6172a5e51aed1ec75303d92332e280fa"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "feb781dcdb9ee16e8f6d6f783059da5a31c9119c58e6fb4928e385f8f92872ac"

[[files]]
file = "journeymap/config/6.0/journeymap.rendering.config"
hash = "59139373798af345188a9a11a0dd317ae39a5749d575cb0dbbfd481732c5caf7"

[[files]]
file = "journeymap/config/6.0/journeymap.topo.config"
hash = "2f6e8125fa9f35e0c700d49c908e0d60216d6d1cced17701351a174995570535"

[[files]]
file = "journeymap/config/6.0/journeymap.waypoint.config"
hash = "373b65a3b7f7f68c9c25b67c66f1e93892f1f504c149bd4d27dfd569ed51b856"

[[files]]
file = "journeymap/config/6.0/journeymap.webmap.config"
hash = "17fbf319709adeec6b71ead4ed0a2fc37210795257ab370c251ec36893c2253c"

[[files]]
file = "journeymap/server/6.0/journeymap.server.default.config"
hash = "5b64bb944f22fd5ab1748e1c6679885786aff0e739e08095fa0f666f4a3c624c"

[[files]]
file = "journeymap/server/6.0/journeymap.server.global.config"
hash = "ebf4c8138b6f982e1df8ca89c203a448556f2c72eef77788baf11ef9c1b6fe7d"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1dccd56d8f5de76f65c521efa05293ab3913bd5c20e5d46a7358eb9859011e9b"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "392d69f52ebe668f15fd449a6b6445215ca12cbf61dbfd39f1c642bc88f3c1a4"
metafile = true

[[files]]
file = "mods/chunks-fade-in.pw.toml"
hash = "104875a5de4e46d3bcb8dadb223ec8933ab326bf869b7db57c09b1f50494e3e3"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "0ce795b587852005f9a254591bb739567fb580a0574b5efbba7842d198f51678"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "6413ed3b9ce3ae6e079c6acf1768d995fd80a9f455350f8a2714f19f5fb548b3"
metafile = true

[[files]]
file = "mods/customskinloader.pw.toml"
hash = "31dfa0ff1c3dcc2052a942fcd633c5f648ffa57060f3fe49856ef0f1a052ef8e"
metafile = true

[[files]]
file = "mods/enchlevel-langpatch.pw.toml"
hash = "9228daaf7287b8d4355651f0529e644e0211a50afe21dda117416bb077d098ba"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "382c8bec74a9dc659ac4a6b018f84cb57e3fd7cc8e17d7813d9c7c53181b3173"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "e8b34e1e436100ba40e75f30a4b82677c5868dd706026af3406f1976e5af9a6c"
metafile = true

[[files]]
file = "mods/fancy-toasts.pw.toml"
hash = "5fb24238e70333d058e197245c8ce1db6ff2cd10cf8124bbbdc90418c8589c02"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1b861203ebfcc4f018bf5ed412f687b3516d0154c854c5888da9313d5bc68756"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "766cc8b67127f0321b838517478adc3afaaa6344ae14d3fed4cbc5dfb9d0ffbe"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "26ca8ef30412fbc86c4b79c22e4bb691ebc1e33a16dca8081a7445fe7048d645"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "4296a6c11eea79dcb4a9e3c32c87929ff1d9ca085fe4ef1f5a1e47b4d19b474b"
metafile = true

[[files]]
file = "mods/minecraft-cursor.pw.toml"
hash = "534bd9344e27b0db234d44d1ea24c9cab67408ac1b6aebc4e8a94a516855aba1"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e2cccb3a1befa656a7896cd31fe8948633b1a136ac41590fa5f031a01530030a"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "7dd6f48cfda61b87daebbb633be566a6ccbe1e27b8e5b1e9dc7d086b7cf1e417"
metafile = true

[[files]]
file = "mods/nemos-inventory-sorting.pw.toml"
hash = "5fcd8190cb5c020af2b44362048f67d7289abaa015016628095f96f88d930552"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "14bab3eceffac221a0e580901a087b71bbc82207a070782ad26a7b01c0985b42"
metafile = true

[[files]]
file = "mods/plasmo-voice.pw.toml"
hash = "56b6dcb30feba17851747334aabea56e131a73c28177ae3361bdc7c487599a1d"
metafile = true

[[files]]
file = "mods/pv-addon-groups.pw.toml"
hash = "dd92a51d8a11901baaad8fdb801798bb8b36830ef06f95ca6f0748b2273f755f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "01431988415a9c9562d4cf505261779705eb24d3aa334acf083317972c47b1a2"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "acbe788fd4e2acfbd8a7c45835f11103f88f7cca985a8e231d0953b4695a5228"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ca79350b2e709cf100bc3418ca57160a82ec203ac7b3395e027970f1137d15b4"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "36d3050f057b2441caee74db85343c7f5a1de51d52376da25a8207ba9a14b458"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "b4e48416bb8cfead5e7815051a7a65a3fb88b075fa8b4935d25da2b23e28af73"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "ba7bd38480d19211874fdfa220e02047ecbde624ad83444d7aca7cfba1f19e3f"
metafile = true

[[files]]
file = "options.txt"
hash = "304b8bad1e8fcb37abcf6bda6a547ba3cf65f3f733c51b1319ef1a26751788b9"

[[files]]
file = "realms_persistence.json"
hash = "cec87653677e1321b959d7f4326ed7acd8ed1c19ad9c24a83044a0138a9f865e"

[[files]]
file = "resourcepacks/clean-bedrock-style-cursors.pw.toml"
hash = "8b937bc0672c1a8abb74a81824f142153112abf865c2c8c60fba0ef51b1e6c9f"
metafile = true

[[files]]
file = "resourcepacks/squareful.pw.toml"
hash = "12c3a1a1063689c1193805e43f4f60e5a59dcd3ea788b9cbf786126596aa00ac"
metafile = true

[[files]]
file = "resourcepacks/summerfields.pw.toml"
hash = "f836c9c6c64eca2592c9db479664e811562a46542c3a674a4f1f193e9a6cb408"
metafile = true

[[files]]
file = "servers.dat"
hash = "dfafc98e373ed194403871ba2272507a41262c6baac66b55dc033614d61083f3"

[[files]]
file = "shaderpacks/bsl.pw.toml"
hash = "e19bbfaf56f0f83fbb9a98676c21fe6f0c8a07300045e30b0068d1e171fc5a8f"
metafile = true

[[files]]
file = "shaderpacks/mellow.pw.toml"
hash = "ca5ca594284a7dc98388c76734bace1f80e4da8f23513ec52d9761f2479f8a76"
metafile = true
