name = "Promised-World-Client-Lite"
author = "ManyStars"
version = "2.2.0+pw.lite.20260103.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47697d61d24283095164266953b8cb8b1c2e15a176ac968806699a200ee547da"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
