name = "Promised-World-Client-Lite"
author = "ManyStars"
version = "2.0.0+pw.lite.20260101"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5cd25e64aaf2c6eb3cae29999ddfb0a15d7a88544bcc108040f131732b48f72"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
