name = "Promised-World-Client-Lite"
author = "ManyStars"
version = "1.0.1+pw.lite.20251226"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99eed22f78922eba0bcce46f62f21baf96658941caa076010225b936a84ed36d"

[versions]
fabric = "0.18.3"
minecraft = "1.21.10"
