name = "Promised-World-Client-Lite"
author = "ManyStars"
version = "1.0.0+pw.lite.20251225"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f441bd30576b51c71ec17173c3d932118f99bb861c2996d2b951c56bbb79836c"

[versions]
fabric = "0.18.3"
minecraft = "1.21.10"
