name = "Promised-World-Client-Lite"
author = "ManyStars"
version = "2.1.0+pw.lite.20260103"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8d53d610199fc612b7cd50d228b849e34d3a5276f69988292803cc91645ae3a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
