name = "Promised-World-Client-Lite"
author = "ManyStars"
version = "1.0.0+pw.lite.20251225"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "120a8ffaa9bf4b792a1c5f18fc32452f551afeb4785ee87ca61a65b45586ef60"

[versions]
fabric = "0.18.3"
minecraft = "1.21.10"
