debug = false
musicHUD = true
notPauseSoundOnGamePause = false
x = 10
y = 10
maxImportList = 300
enableCache = false
globalCache = false
selectHudSize = 0.7
selectHudCount = 5
selectHudShowArtist = true
glowingText = false
oldGUI = false
noVIP = false
only5Second = false
allowLyricToServer = false
