name = "Promised-World-Client-Full"
author = "ManyStars"
version = "3.1.0+pw.full.20251227"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e2c051587fb18532c8eaca4628e66467973ef06530b8538237d092faf966642"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
