name = "Promised-World-Client-Full"
author = "ManyStars"
version = "3.4.0+pw.full.20260103"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9524d37eadc78c1048bf6b407fa6e4731839c9af25da5bbf19d6959b28fe3daa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
