name = "Promised-World-Client-Full"
author = "ManyStars"
version = "3.0.0+pw.full.20251225"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dea9b19d8c7d44f5e889e58e0e8ceba30fdf520d75a40a3968f554206f53f31"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
