name = "Promised-World-Client-Full"
author = "ManyStars"
version = "3.0.0+pw.full.20251225"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c15a3e912a1399ece86641800e91b5996794d42aeedadb0e6b4c373d3927fa1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
