name = "Promised-World-Client-Full"
author = "ManyStars"
version = "3.2.0+pw.full.20251227.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e381a601482f056aea2cb492c5787863295aabb72a0f1cc661bd5423b7568683"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
